package com.cucumber.utils.engineering.match.condition;

public enum MatchCondition {
    JSON_NON_EXTENSIBLE_OBJECT,
    JSON_NON_EXTENSIBLE_ARRAY,
    JSON_STRICT_ORDER_ARRAY,
    XML_CHILD_NODELIST_LENGTH,
    XML_CHILD_NODELIST_SEQUENCE,
    XML_ELEMENT_NUM_ATTRIBUTES,
    DO_NOT_MATCH,
    DO_NOT_MATCH_HTTP_RESPONSE_BY_STATUS,
    DO_NOT_MATCH_HTTP_RESPONSE_BY_BODY,
    DO_NOT_MATCH_HTTP_RESPONSE_BY_HEADERS,
    DO_NOT_MATCH_HTTP_RESPONSE_BY_REASON
}
