theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: Cucumber JUtils
description: An extension of Cucumber for Java with a set of commonly used utilities
author: Florin Slevoaca
url: https://fslev.github.io/cucumber-jutils
permalink: pretty