remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

title: "Cucumber JUtils"
tagline: "An extension to Cucumber for Java, with scenario variables and assertion support"
description: "It augments your Cucumber based test framework with some powerful features like: scenario scoped variables, assertions, SpEL plus some Utilities pre-defined steps and classes"
author: "Florin Slevoaca"
url: "https://fslev.github.io/cucumber-jutils"
permalink: pretty